[2019-08-10 06:30:31,776] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-10 06:30:37,378] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused: no further information (org.apache.zookeeper.ClientCnxn)
[2019-08-10 06:30:39,680] ERROR Error while writing to checkpoint file C:\tmp\kafka-logs\log-start-offset-checkpoint (kafka.server.LogDirFailureChannel)
java.nio.file.FileAlreadyExistsException: C:\tmp\kafka-logs\log-start-offset-checkpoint.tmp -> C:\tmp\kafka-logs\log-start-offset-checkpoint
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:809)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:72)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:59)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1$$anonfun$apply$34.apply(LogManager.scala:611)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1$$anonfun$apply$34.apply(LogManager.scala:605)
	at scala.Option.foreach(Option.scala:257)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1.apply(LogManager.scala:605)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1.apply(LogManager.scala:604)
	at scala.Option.foreach(Option.scala:257)
	at kafka.log.LogManager.kafka$log$LogManager$$checkpointLogStartOffsetsInDir(LogManager.scala:604)
	at kafka.log.LogManager$$anonfun$checkpointLogStartOffsets$1.apply(LogManager.scala:577)
	at kafka.log.LogManager$$anonfun$checkpointLogStartOffsets$1.apply(LogManager.scala:577)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at kafka.log.LogManager.checkpointLogStartOffsets(LogManager.scala:577)
	at kafka.log.LogManager$$anonfun$startup$4.apply$mcV$sp(LogManager.scala:411)
	at kafka.utils.KafkaScheduler$$anonfun$1.apply$mcV$sp(KafkaScheduler.scala:114)
	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.file.AccessDeniedException: C:\tmp\kafka-logs\log-start-offset-checkpoint.tmp -> C:\tmp\kafka-logs\log-start-offset-checkpoint
		at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
		at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
		at java.nio.file.Files.move(Unknown Source)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:806)
		... 25 more
[2019-08-10 06:30:41,455] INFO [ReplicaManager broker=0] Stopping serving replicas in dir C:\tmp\kafka-logs (kafka.server.ReplicaManager)
[2019-08-10 06:30:41,494] ERROR Uncaught exception in scheduled task 'kafka-log-start-offset-checkpoint' (kafka.utils.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: Error while writing to checkpoint file C:\tmp\kafka-logs\log-start-offset-checkpoint
Caused by: java.nio.file.FileAlreadyExistsException: C:\tmp\kafka-logs\log-start-offset-checkpoint.tmp -> C:\tmp\kafka-logs\log-start-offset-checkpoint
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:809)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:72)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:59)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1$$anonfun$apply$34.apply(LogManager.scala:611)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1$$anonfun$apply$34.apply(LogManager.scala:605)
	at scala.Option.foreach(Option.scala:257)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1.apply(LogManager.scala:605)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1.apply(LogManager.scala:604)
	at scala.Option.foreach(Option.scala:257)
	at kafka.log.LogManager.kafka$log$LogManager$$checkpointLogStartOffsetsInDir(LogManager.scala:604)
	at kafka.log.LogManager$$anonfun$checkpointLogStartOffsets$1.apply(LogManager.scala:577)
	at kafka.log.LogManager$$anonfun$checkpointLogStartOffsets$1.apply(LogManager.scala:577)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at kafka.log.LogManager.checkpointLogStartOffsets(LogManager.scala:577)
	at kafka.log.LogManager$$anonfun$startup$4.apply$mcV$sp(LogManager.scala:411)
	at kafka.utils.KafkaScheduler$$anonfun$1.apply$mcV$sp(KafkaScheduler.scala:114)
	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.file.AccessDeniedException: C:\tmp\kafka-logs\log-start-offset-checkpoint.tmp -> C:\tmp\kafka-logs\log-start-offset-checkpoint
		at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
		at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
		at java.nio.file.Files.move(Unknown Source)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:806)
		... 25 more
[2019-08-10 06:30:41,635] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions Set(__consumer_offsets-22, topic-7-0, __consumer_offsets-30, __consumer_offsets-8, topic-5-7, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, topic-4-9, topic-4-11, __consumer_offsets-9, __consumer_offsets-46, topic-4-6, topic-4-2, topic-3-1, topic-2-0, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, topic-6-0, topic-7-1, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, topic-5-3, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, topic-4-10, topic-4-1, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-37, topic-4-8, topic-3-0, __consumer_offsets-15, __consumer_offsets-24, topic-5-2, __consumer_offsets-38, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, topic-4-3, __consumer_offsets-11, topic-6-2, topic-4-7, topic-4-4, topic-4-0, __consumer_offsets-13, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, topic-5-1, topic-5-4, topic-1-0, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, topic-4-5, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, topic-7-2, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40, topic-6-1) (kafka.server.ReplicaFetcherManager)
[2019-08-10 06:30:42,218] INFO [ReplicaAlterLogDirsManager on broker 0] Removed fetcher for partitions Set(__consumer_offsets-22, topic-7-0, __consumer_offsets-30, __consumer_offsets-8, topic-5-7, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, topic-4-9, topic-4-11, __consumer_offsets-9, __consumer_offsets-46, topic-4-6, topic-4-2, topic-3-1, topic-2-0, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, topic-6-0, topic-7-1, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, topic-5-3, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, topic-4-10, topic-4-1, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-37, topic-4-8, topic-3-0, __consumer_offsets-15, __consumer_offsets-24, topic-5-2, __consumer_offsets-38, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, topic-4-3, __consumer_offsets-11, topic-6-2, topic-4-7, topic-4-4, topic-4-0, __consumer_offsets-13, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, topic-5-1, topic-5-4, topic-1-0, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, topic-4-5, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, topic-7-2, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40, topic-6-1) (kafka.server.ReplicaAlterLogDirsManager)
[2019-08-10 06:30:42,888] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-08-10 06:30:43,821] INFO [ReplicaManager broker=0] Broker 0 stopped fetcher for partitions __consumer_offsets-22,topic-7-0,__consumer_offsets-30,__consumer_offsets-8,topic-5-7,__consumer_offsets-21,__consumer_offsets-4,__consumer_offsets-27,__consumer_offsets-7,topic-4-9,topic-4-11,__consumer_offsets-9,__consumer_offsets-46,topic-4-6,topic-4-2,topic-3-1,topic-2-0,__consumer_offsets-25,__consumer_offsets-35,__consumer_offsets-41,__consumer_offsets-33,__consumer_offsets-23,__consumer_offsets-49,topic-6-0,topic-7-1,__consumer_offsets-47,__consumer_offsets-16,__consumer_offsets-28,topic-5-3,__consumer_offsets-31,__consumer_offsets-36,__consumer_offsets-42,topic-4-10,topic-4-1,__consumer_offsets-3,__consumer_offsets-18,__consumer_offsets-37,topic-4-8,topic-3-0,__consumer_offsets-15,__consumer_offsets-24,topic-5-2,__consumer_offsets-38,__consumer_offsets-17,__consumer_offsets-48,__consumer_offsets-19,topic-4-3,__consumer_offsets-11,topic-6-2,topic-4-7,topic-4-4,topic-4-0,__consumer_offsets-13,__consumer_offsets-2,__consumer_offsets-43,__consumer_offsets-6,__consumer_offsets-14,topic-5-1,topic-5-4,topic-1-0,__consumer_offsets-20,__consumer_offsets-0,__consumer_offsets-44,__consumer_offsets-39,__consumer_offsets-12,topic-4-5,__consumer_offsets-45,__consumer_offsets-1,__consumer_offsets-5,__consumer_offsets-26,topic-7-2,__consumer_offsets-29,__consumer_offsets-34,__consumer_offsets-10,__consumer_offsets-32,__consumer_offsets-40,topic-6-1 and stopped moving logs for partitions  because they are in the failed log directory C:\tmp\kafka-logs. (kafka.server.ReplicaManager)
[2019-08-10 06:30:44,042] INFO Stopping serving logs in dir C:\tmp\kafka-logs (kafka.log.LogManager)
[2019-08-10 06:30:44,360] ERROR Shutdown broker because all log dirs in C:\tmp\kafka-logs have failed (kafka.log.LogManager)
