[2019-08-08 09:55:04,561] INFO Expiring session 0x100018dfbec0000, timeout of 6000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2019-08-08 09:55:09,672] INFO Processed session termination for sessionid: 0x100018dfbec0000 (org.apache.zookeeper.server.PrepRequestProcessor)
[2019-08-08 09:55:03,866] WARN Client session timed out, have not heard from server in 56415999ms for sessionid 0x100018dfbec0000 (org.apache.zookeeper.ClientCnxn)
[2019-08-08 09:55:10,312] INFO Client session timed out, have not heard from server in 56415999ms for sessionid 0x100018dfbec0000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-08-08 09:55:10,303] INFO Closed socket connection for client /127.0.0.1:58959 which had sessionid 0x100018dfbec0000 (org.apache.zookeeper.server.NIOServerCnxn)
[2019-08-08 09:55:08,240] ERROR Error while writing to checkpoint file C:\tmp\kafka-logs\log-start-offset-checkpoint (kafka.server.LogDirFailureChannel)
java.nio.file.FileAlreadyExistsException: C:\tmp\kafka-logs\log-start-offset-checkpoint.tmp -> C:\tmp\kafka-logs\log-start-offset-checkpoint
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:809)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:72)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:59)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1$$anonfun$apply$34.apply(LogManager.scala:611)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1$$anonfun$apply$34.apply(LogManager.scala:605)
	at scala.Option.foreach(Option.scala:257)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1.apply(LogManager.scala:605)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1.apply(LogManager.scala:604)
	at scala.Option.foreach(Option.scala:257)
	at kafka.log.LogManager.kafka$log$LogManager$$checkpointLogStartOffsetsInDir(LogManager.scala:604)
	at kafka.log.LogManager$$anonfun$checkpointLogStartOffsets$1.apply(LogManager.scala:577)
	at kafka.log.LogManager$$anonfun$checkpointLogStartOffsets$1.apply(LogManager.scala:577)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at kafka.log.LogManager.checkpointLogStartOffsets(LogManager.scala:577)
	at kafka.log.LogManager$$anonfun$startup$4.apply$mcV$sp(LogManager.scala:411)
	at kafka.utils.KafkaScheduler$$anonfun$1.apply$mcV$sp(KafkaScheduler.scala:114)
	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.file.AccessDeniedException: C:\tmp\kafka-logs\log-start-offset-checkpoint.tmp -> C:\tmp\kafka-logs\log-start-offset-checkpoint
		at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
		at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
		at java.nio.file.Files.move(Unknown Source)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:806)
		... 25 more
[2019-08-08 09:55:03,867] INFO [GroupCoordinator 0]: Member consumer-1-3b78184b-d6d5-4288-8135-5a67c5792245 in group console-consumer-36462 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-08-08 09:55:10,362] INFO [ReplicaManager broker=0] Stopping serving replicas in dir C:\tmp\kafka-logs (kafka.server.ReplicaManager)
[2019-08-08 09:55:10,362] ERROR Uncaught exception in scheduled task 'kafka-log-start-offset-checkpoint' (kafka.utils.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: Error while writing to checkpoint file C:\tmp\kafka-logs\log-start-offset-checkpoint
Caused by: java.nio.file.FileAlreadyExistsException: C:\tmp\kafka-logs\log-start-offset-checkpoint.tmp -> C:\tmp\kafka-logs\log-start-offset-checkpoint
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:809)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:72)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:59)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1$$anonfun$apply$34.apply(LogManager.scala:611)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1$$anonfun$apply$34.apply(LogManager.scala:605)
	at scala.Option.foreach(Option.scala:257)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1.apply(LogManager.scala:605)
	at kafka.log.LogManager$$anonfun$kafka$log$LogManager$$checkpointLogStartOffsetsInDir$1.apply(LogManager.scala:604)
	at scala.Option.foreach(Option.scala:257)
	at kafka.log.LogManager.kafka$log$LogManager$$checkpointLogStartOffsetsInDir(LogManager.scala:604)
	at kafka.log.LogManager$$anonfun$checkpointLogStartOffsets$1.apply(LogManager.scala:577)
	at kafka.log.LogManager$$anonfun$checkpointLogStartOffsets$1.apply(LogManager.scala:577)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at kafka.log.LogManager.checkpointLogStartOffsets(LogManager.scala:577)
	at kafka.log.LogManager$$anonfun$startup$4.apply$mcV$sp(LogManager.scala:411)
	at kafka.utils.KafkaScheduler$$anonfun$1.apply$mcV$sp(KafkaScheduler.scala:114)
	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.nio.file.AccessDeniedException: C:\tmp\kafka-logs\log-start-offset-checkpoint.tmp -> C:\tmp\kafka-logs\log-start-offset-checkpoint
		at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
		at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
		at java.nio.file.Files.move(Unknown Source)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:806)
		... 25 more
[2019-08-08 09:55:10,681] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions Set(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-37, __consumer_offsets-15, __consumer_offsets-24, __consumer_offsets-38, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, __consumer_offsets-13, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, topic-1-0, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaFetcherManager)
[2019-08-08 09:55:10,636] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-36462 in state PreparingRebalance with old generation 1 (__consumer_offsets-32) (reason: removing member consumer-1-3b78184b-d6d5-4288-8135-5a67c5792245 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-08-08 09:55:10,713] INFO [ReplicaAlterLogDirsManager on broker 0] Removed fetcher for partitions Set(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-37, __consumer_offsets-15, __consumer_offsets-24, __consumer_offsets-38, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, __consumer_offsets-13, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, topic-1-0, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaAlterLogDirsManager)
[2019-08-08 09:55:10,720] INFO [GroupCoordinator 0]: Group console-consumer-36462 with generation 2 is now empty (__consumer_offsets-32) (kafka.coordinator.group.GroupCoordinator)
[2019-08-08 09:55:10,867] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-36462 in state PreparingRebalance with old generation 2 (__consumer_offsets-32) (reason: Adding new member consumer-1-5297c317-1a25-4af2-8a44-f59e832c61bf) (kafka.coordinator.group.GroupCoordinator)
[2019-08-08 09:55:10,897] INFO [ReplicaManager broker=0] Broker 0 stopped fetcher for partitions __consumer_offsets-22,__consumer_offsets-30,__consumer_offsets-8,__consumer_offsets-21,__consumer_offsets-4,__consumer_offsets-27,__consumer_offsets-7,__consumer_offsets-9,__consumer_offsets-46,__consumer_offsets-25,__consumer_offsets-35,__consumer_offsets-41,__consumer_offsets-33,__consumer_offsets-23,__consumer_offsets-49,__consumer_offsets-47,__consumer_offsets-16,__consumer_offsets-28,__consumer_offsets-31,__consumer_offsets-36,__consumer_offsets-42,__consumer_offsets-3,__consumer_offsets-18,__consumer_offsets-37,__consumer_offsets-15,__consumer_offsets-24,__consumer_offsets-38,__consumer_offsets-17,__consumer_offsets-48,__consumer_offsets-19,__consumer_offsets-11,__consumer_offsets-13,__consumer_offsets-2,__consumer_offsets-43,__consumer_offsets-6,__consumer_offsets-14,topic-1-0,__consumer_offsets-20,__consumer_offsets-0,__consumer_offsets-44,__consumer_offsets-39,__consumer_offsets-12,__consumer_offsets-45,__consumer_offsets-1,__consumer_offsets-5,__consumer_offsets-26,__consumer_offsets-29,__consumer_offsets-34,__consumer_offsets-10,__consumer_offsets-32,__consumer_offsets-40 and stopped moving logs for partitions  because they are in the failed log directory C:\tmp\kafka-logs. (kafka.server.ReplicaManager)
[2019-08-08 09:55:10,964] INFO [GroupCoordinator 0]: Stabilized group console-consumer-36462 generation 3 (__consumer_offsets-32) (kafka.coordinator.group.GroupCoordinator)
[2019-08-08 09:55:11,038] INFO Stopping serving logs in dir C:\tmp\kafka-logs (kafka.log.LogManager)
[2019-08-08 09:55:11,140] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-36462 in state PreparingRebalance with old generation 3 (__consumer_offsets-32) (reason: Adding new member consumer-1-fcd8335b-c841-4e10-ba4d-c0e6341a3fa8) (kafka.coordinator.group.GroupCoordinator)
[2019-08-08 09:55:11,195] ERROR Shutdown broker because all log dirs in C:\tmp\kafka-logs have failed (kafka.log.LogManager)
